variable aws_region {}
variable aws_access_key {}
variable aws_secret_access_key {}
variable vpc_cidr_block {}
variable env_prefix {}
variable subnet_cidr_block {}
variable avail_zone {}
variable my_public_ip {}
variable instance_type {}
variable public_key_location {}
variable image_name {}